# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Car_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1043, 974)
        self.layout_MainVertical = QtWidgets.QVBoxLayout(Form)
        self.layout_MainVertical.setObjectName("layout_MainVertical")
        self.grp_Inputs = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grp_Inputs.setFont(font)
        self.grp_Inputs.setObjectName("grp_Inputs")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_Inputs)
        self.gridLayout.setObjectName("gridLayout")
        self.le_c1 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_c1.sizePolicy().hasHeightForWidth())
        self.le_c1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_c1.setFont(font)
        self.le_c1.setObjectName("le_c1")
        self.gridLayout.addWidget(self.le_c1, 3, 1, 1, 1)
        self.lbl_m2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_m2.sizePolicy().hasHeightForWidth())
        self.lbl_m2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_m2.setFont(font)
        self.lbl_m2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_m2.setObjectName("lbl_m2")
        self.gridLayout.addWidget(self.lbl_m2, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_RampANgle = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_RampANgle.sizePolicy().hasHeightForWidth())
        self.lbl_RampANgle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_RampANgle.setFont(font)
        self.lbl_RampANgle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_RampANgle.setObjectName("lbl_RampANgle")
        self.gridLayout.addWidget(self.lbl_RampANgle, 6, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_k2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_k2.sizePolicy().hasHeightForWidth())
        self.lbl_k2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_k2.setFont(font)
        self.lbl_k2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_k2.setObjectName("lbl_k2")
        self.gridLayout.addWidget(self.lbl_k2, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.le_AngDeg = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_AngDeg.sizePolicy().hasHeightForWidth())
        self.le_AngDeg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_AngDeg.setFont(font)
        self.le_AngDeg.setObjectName("le_AngDeg")
        self.gridLayout.addWidget(self.le_AngDeg, 6, 1, 1, 1)
        self.le_CarSpeed = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_CarSpeed.sizePolicy().hasHeightForWidth())
        self.le_CarSpeed.setSizePolicy(sizePolicy)
        self.le_CarSpeed.setObjectName("le_CarSpeed")
        self.gridLayout.addWidget(self.le_CarSpeed, 1, 1, 1, 1)
        self.le_m2 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_m2.sizePolicy().hasHeightForWidth())
        self.le_m2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_m2.setFont(font)
        self.le_m2.setObjectName("le_m2")
        self.gridLayout.addWidget(self.le_m2, 4, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 10, 0, 1, 1)
        self.btn_calculate = QtWidgets.QPushButton(self.grp_Inputs)
        self.btn_calculate.setObjectName("btn_calculate")
        self.gridLayout.addWidget(self.btn_calculate, 8, 1, 1, 1)
        self.lbl_CarSpeed = QtWidgets.QLabel(self.grp_Inputs)
        self.lbl_CarSpeed.setObjectName("lbl_CarSpeed")
        self.gridLayout.addWidget(self.lbl_CarSpeed, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.le_mcar = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_mcar.sizePolicy().hasHeightForWidth())
        self.le_mcar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_mcar.setFont(font)
        self.le_mcar.setObjectName("le_mcar")
        self.gridLayout.addWidget(self.le_mcar, 0, 1, 1, 1)
        self.le_tMax = QtWidgets.QLineEdit(self.grp_Inputs)
        self.le_tMax.setObjectName("le_tMax")
        self.gridLayout.addWidget(self.le_tMax, 7, 1, 1, 1)
        self.le_k1 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_k1.sizePolicy().hasHeightForWidth())
        self.le_k1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_k1.setFont(font)
        self.le_k1.setObjectName("le_k1")
        self.gridLayout.addWidget(self.le_k1, 2, 1, 1, 1)
        self.le_k2 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_k2.sizePolicy().hasHeightForWidth())
        self.le_k2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_k2.setFont(font)
        self.le_k2.setObjectName("le_k2")
        self.gridLayout.addWidget(self.le_k2, 5, 1, 1, 1)
        self.lbl_tMax = QtWidgets.QLabel(self.grp_Inputs)
        self.lbl_tMax.setObjectName("lbl_tMax")
        self.gridLayout.addWidget(self.lbl_tMax, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_Spring1 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Spring1.sizePolicy().hasHeightForWidth())
        self.lbl_Spring1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Spring1.setFont(font)
        self.lbl_Spring1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Spring1.setObjectName("lbl_Spring1")
        self.gridLayout.addWidget(self.lbl_Spring1, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_CarBodyMass = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CarBodyMass.sizePolicy().hasHeightForWidth())
        self.lbl_CarBodyMass.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_CarBodyMass.setFont(font)
        self.lbl_CarBodyMass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_CarBodyMass.setObjectName("lbl_CarBodyMass")
        self.gridLayout.addWidget(self.lbl_CarBodyMass, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_Dashpot = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Dashpot.sizePolicy().hasHeightForWidth())
        self.lbl_Dashpot.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_Dashpot.setFont(font)
        self.lbl_Dashpot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Dashpot.setObjectName("lbl_Dashpot")
        self.gridLayout.addWidget(self.lbl_Dashpot, 3, 0, 1, 1)
        self.pb_Optimize = QtWidgets.QPushButton(self.grp_Inputs)
        self.pb_Optimize.setObjectName("pb_Optimize")
        self.gridLayout.addWidget(self.pb_Optimize, 9, 1, 1, 1)
        self.layout_MainVertical.addWidget(self.grp_Inputs, 0, QtCore.Qt.AlignLeft)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grp_Inputs.setTitle(_translate("Form", "Model Inputs"))
        self.le_c1.setText(_translate("Form", "4500"))
        self.lbl_m2.setText(_translate("Form", "Wheel mass (m2, kg)"))
        self.lbl_RampANgle.setText(_translate("Form", "Ramp Angle (deg)"))
        self.lbl_k2.setText(_translate("Form", "Tire spring constant (k2, N/m)"))
        self.le_AngDeg.setText(_translate("Form", "45"))
        self.le_CarSpeed.setText(_translate("Form", "120"))
        self.le_m2.setText(_translate("Form", "20"))
        self.btn_calculate.setText(_translate("Form", "Calculate"))
        self.lbl_CarSpeed.setText(_translate("Form", "Car Speed (kph)"))
        self.le_mcar.setText(_translate("Form", "450"))
        self.le_tMax.setText(_translate("Form", "3"))
        self.le_k1.setText(_translate("Form", "15000"))
        self.le_k2.setText(_translate("Form", "90000"))
        self.lbl_tMax.setText(_translate("Form", "t, max plot (s)"))
        self.lbl_Spring1.setText(_translate("Form", "Suspension Spring (k1, N/m)"))
        self.lbl_CarBodyMass.setText(_translate("Form", "Car body mass (m1, kg)"))
        self.lbl_Dashpot.setText(_translate("Form", "Suspension Shock Absorber (c1, N*s/m)"))
        self.pb_Optimize.setText(_translate("Form", "Optimize Suspension"))

